In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
# Read in csv
birth_path = 'Birth_Rate_Data_Project_stater.csv'
birth_data_df = pd.read_csv(birth_path)

birth_data_df

,Unnamed: 0,2012,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95
0,NaN,NaN,NaN,Age-specific fertility rates,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Age-specific fertility rates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Estimated resident population,Births,15–19 years,20-24 years,25-29 years,30-34 years,35-39 years,40-44 years,45-49 years,...,Births,15–19 years,20-24 years,25-29 years,30-34 years,35-39 years,40-44 years,45-49 years,Total fertility rate,Median age of mother
2,NaN,persons,no.,rate,rate,rate,rate,rate,rate,rate,...,no.,rate,rate,rate,rate,rate,rate,rate,rate,years
3,Greater Sydney,"4,677,196","66,474",10.0,41.7,93.0,128.9,81.5,19.0,1.1,...,"66,657",5.4,29.9,74.9,117.5,79.4,19.3,1.7,1.64,32.1
4,Rest of NSW,"2,627,048","31,583",22.9,81.0,133.2,126.6,59.1,11.4,0.6,...,"31,493",15.0,67.1,119.8,125.7,60.8,11.8,0.7,2.00,30.0
5,Total New South Wales,"7,304,244","98,508",14.9,54.1,104.4,128.8,74.8,16.5,1.0,...,"98,906",9.1,41.3,87.7,120.8,74.7,17.1,1.4,1.76,31.5
6,Greater Melbourne,"4,265,843","59,997",6.9,31.9,84.0,127.5,80.5,17.6,1.1,...,"60,764",3.9,23.1,68.6,116.6,78.1,18.4,1.7,1.55,32.3
7,Rest of Vic.,"1,385,248","17,282",16.9,68.1,129.1,132.3,61.9,12.1,0.5,...,"16,155",10.7,58.9,114.1,127.5,63.0,13.0,0.8,1.94,30.5
8,Total Victoria,"5,651,091","77,405",9.5,39.0,92.2,128.5,76.6,16.4,1.0,...,"77,220",5.6,29.7,76.6,118.8,75.5,17.3,1.5,1.63,32.0
9,Greater Brisbane,"2,196,288","31,361",18.9,55.9,102.0,124.0,68.8,14.7,0.8,...,"31,646",11.2,44.4,84.8,111.7,67.1,13.9,1.1,1.67,31.0
10,Rest of Qld,"2,372,399","32,355",27.0,83.0,126.2,121.5,59.4,11.8,0.6,...,"30,005",15.6,67.4,108.1,110.8,57.1,12.0,0.8,1.86,29.9
11,Total Queensland,"4,568,687","63,837",23.1,68.7,113.5,122.9,64.2,13.2,0.7,...,"61,735",13.4,54.8,95.5,111.4,62.4,13.0,1.0,1.76,30.5
12,Greater Adelaide,"1,277,850","15,975",13.3,43.8,100.4,124.4,66.6,13.8,0.8,...,"15,585",6.4,32.5,84.8,118.8,67.5,14.7,1.2,1.63,31.6
13,Rest of SA,"378,875","4,452",24.4,98.1,141.8,119.7,50.8,9.9,0.4,...,"3,895",13.1,81.5,125.0,111.5,52.8,8.4,0.6,1.96,29.4
14,Total South Australia,"1,656,725","20,433",15.7,52.7,107.9,123.5,63.4,12.9,0.7,...,"19,490",7.9,40.4,92.0,117.6,64.8,13.4,1.1,1.69,31.2
15,Greater Perth,"1,892,862","25,921",14.9,48.3,97.0,125.2,68.5,14.4,0.8,...,"26,654",7.4,38.9,89.4,120.2,72.2,15.5,1.2,1.72,31.6
16,Rest of WA,"532,645","7,614",35.2,98.7,131.7,118.3,55.7,11.4,0.5,...,"6,621",21.6,89.4,123.8,113.0,56.6,10.2,0.6,2.08,29.9
17,Total West Australia,"2,425,507","33,627",19.1,57.3,104.0,123.9,65.8,13.8,0.8,...,"33,539",10.9,47.4,96.0,119.4,69.5,14.5,1.1,1.79,31.3
18,Greater Hobart,"217,670","2,740",23.8,61.2,110.8,126.3,71.3,13.6,0.7,...,"2,717",11.5,44.3,89.6,118.7,66.7,13.5,0.8,1.72,31.1
19,Rest of Tas.,"294,054","3,397",23.8,90.1,133.9,114.2,50.3,10.7,0.6,...,"3,018",14.0,73.1,113.6,107.6,50.1,10.7,0.4,1.85,29.4
20,Total Tasmania,"511,724","6,168",23.9,76.6,123.4,120.1,59.6,11.9,0.6,...,"5,741",12.9,59.4,102.5,113.2,58.1,12.0,0.6,1.79,30.2
21,Greater Darwin,"133,105","2,206",23.3,75.3,102.5,111.5,64.2,15.8,0.8,...,"2,141",13.3,62.8,91.6,106.4,65.1,15.4,1.4,1.78,30.9
22,Rest of NT,"102,810","1,893",77.6,114.6,108.0,100.2,52.6,11.8,0.3,...,"1,511",57.1,111.9,91.8,91.5,51.5,10.1,0.7,2.07,27.8
23,Total Northern Territory,"235,915","4,104",49.7,93.6,105.1,106.8,59.4,14.2,0.6,...,"3,658",33.4,85.0,92.1,100.9,60.0,13.3,1.1,1.93,29.8
24,Total Australian Capital Territory,"376,539","5,461",8.7,31.3,86.6,131.7,77.3,17.1,0.8,...,"5,520",5.5,23.4,78.8,126.8,79.1,17.2,1.5,1.66,32.2
25,AUSTRALIA,"22,733,465","309,582",16.3,53.9,103.3,126.3,71.0,15.2,0.9,...,"305,832",9.5,41.8,87.4,117.8,70.9,15.7,1.3,1.72,31.4